image: node:12

definitions:
  steps:
    - step: &test
        caches:
          - node
        name: test
        script:
          - mv .npmrc_config .npmrc
          - yarn install --production=false
          - yarn test:types
          - yarn test:lint
          - yarn test:unit --ci
    - step: &build
        caches:
          - node
        artifacts:
          - lib/**
        name: build
        script:
          - mv .npmrc_config .npmrc
          - yarn install --production=false
          - yarn build
    - step: &publish
        name: publish
        script:
          - mv .npmrc_config .npmrc
          - yarn publish --tag $BITBUCKET_TAG

pipelines:
  branches:
    master:
      - step: *test
      - step: *build

  pull-requests:
    "**":
      - step: *test
      - step: *build

  tags:
    "**":
      - step: *test
      - step: *build
      - step: *publish

